-- V3xadoUI UI Library - Project Information
-- This is a Roblox UI library that requires the Roblox game environment to run

print("=====================================")
print("V3xadoUI UI Library")
print("=====================================")
print("")
print("This is a Roblox Lua UI library.")
print("")
print("Project Files:")
print("  - source.lua: Main library source code")
print("  - icons.lua: Icon definitions")
print("  - example.lua: Example usage")
print("")
print("Note: This library requires the Roblox game environment to run.")
print("=====================================")
print("")
print("File listing is disabled in Roblox Lua (no external file access).")
print("")
print("=====================================")